/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as AuthCheckEmailRouteImport } from './routes/auth/check-email'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth/verify-otp'
import { Route as DeviceIndexRouteImport } from './routes/device/index'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as McpAuthorizeRouteImport } from './routes/mcp.authorize'
import { Route as PublicProjectProjectIdRouteImport } from './routes/public-project.$projectId'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'
import { Route as LayoutAuthenticatedProfileSetupRouteImport } from './routes/_layout/_authenticated/profile-setup'
import { Route as LayoutAuthenticatedDashboardIndexRouteImport } from './routes/_layout/_authenticated/dashboard/index'
import { Route as LayoutAuthenticatedDashboardSettingsRouteImport } from './routes/_layout/_authenticated/dashboard/settings'
import { Route as LayoutAuthenticatedDashboardSettingsAccountRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId'
import { Route as LayoutAuthenticatedDashboardTeamCreateRouteImport } from './routes/_layout/_authenticated/dashboard/team/create'
import { Route as LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/developer'
import { Route as LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/information'
import { Route as LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/notifications'
import { Route as LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport } from './routes/_layout/_authenticated/dashboard/settings/account/preferences'
import { Route as LayoutAuthenticatedDashboardSettingsAdminAiRouteImport } from './routes/_layout/_authenticated/dashboard/settings/admin/ai'
import { Route as LayoutAuthenticatedDashboardSettingsAdminTeamsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/admin/teams'
import { Route as LayoutAuthenticatedDashboardSettingsAdminUsersRouteImport } from './routes/_layout/_authenticated/dashboard/settings/admin/users'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/index'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdMembersRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/members'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdSearchRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/search'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
import { Route as LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport } from './routes/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
import { Route as LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRouteImport } from './routes/_layout/_authenticated/dashboard/settings/admin/teams/$teamId/labels'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/index'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/backlog'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/board'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/chat'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/gantt'
import { Route as LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRouteImport } from './routes/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/task/$taskId_'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRoute,
} as any)
const DeviceIndexRoute = DeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeviceRoute,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => DeviceRoute,
} as any)
const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: '/mcp/authorize',
  path: '/mcp/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProjectProjectIdRoute = PublicProjectProjectIdRouteImport.update({
  id: '/public-project/$projectId',
  path: '/public-project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedProfileSetupRoute =
  LayoutAuthenticatedProfileSetupRouteImport.update({
    id: '/profile-setup',
    path: '/profile-setup',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedDashboardIndexRoute =
  LayoutAuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsRoute =
  LayoutAuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountRoute =
  LayoutAuthenticatedDashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProjectsRoute =
  LayoutAuthenticatedDashboardSettingsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardTeamTeamIdRoute =
  LayoutAuthenticatedDashboardTeamTeamIdRouteImport.update({
    id: '/team/$teamId',
    path: '/team/$teamId',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardTeamCreateRoute =
  LayoutAuthenticatedDashboardTeamCreateRouteImport.update({
    id: '/team/create',
    path: '/team/create',
    getParentRoute: () => LayoutAuthenticatedDashboardRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute =
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountInformationRoute =
  LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute =
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute =
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAccountRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAdminAiRoute =
  LayoutAuthenticatedDashboardSettingsAdminAiRouteImport.update({
    id: '/admin/ai',
    path: '/admin/ai',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAdminTeamsRoute =
  LayoutAuthenticatedDashboardSettingsAdminTeamsRouteImport.update({
    id: '/admin/teams',
    path: '/admin/teams',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsAdminUsersRoute =
  LayoutAuthenticatedDashboardSettingsAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsRoute,
  } as any)
const LayoutAuthenticatedDashboardTeamTeamIdIndexRoute =
  LayoutAuthenticatedDashboardTeamTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
  } as any)
const LayoutAuthenticatedDashboardTeamTeamIdMembersRoute =
  LayoutAuthenticatedDashboardTeamTeamIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
  } as any)
const LayoutAuthenticatedDashboardTeamTeamIdSearchRoute =
  LayoutAuthenticatedDashboardTeamTeamIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
  } as any)
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport.update(
    {
      id: '/$projectId/general',
      path: '/$projectId/general',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport.update(
    {
      id: '/$projectId/integrations',
      path: '/$projectId/integrations',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport.update(
    {
      id: '/$projectId/visibility',
      path: '/$projectId/visibility',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute =
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport.update(
    {
      id: '/$projectId/workflow',
      path: '/$projectId/workflow',
      getParentRoute: () => LayoutAuthenticatedDashboardSettingsProjectsRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRoute =
  LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRouteImport.update({
    id: '/$teamId/labels',
    path: '/$teamId/labels',
    getParentRoute: () => LayoutAuthenticatedDashboardSettingsAdminTeamsRoute,
  } as any)
const LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRoute =
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRouteImport.update(
    {
      id: '/project/$projectId/',
      path: '/project/$projectId/',
      getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRoute =
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRouteImport.update(
    {
      id: '/project/$projectId/backlog',
      path: '/project/$projectId/backlog',
      getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRoute =
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRouteImport.update(
    {
      id: '/project/$projectId/board',
      path: '/project/$projectId/board',
      getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRoute =
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRouteImport.update({
    id: '/project/$projectId/chat',
    path: '/project/$projectId/chat',
    getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
  } as any)
const LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRoute =
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRouteImport.update(
    {
      id: '/project/$projectId/gantt',
      path: '/project/$projectId/gantt',
      getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
    } as any,
  )
const LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRoute =
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRouteImport.update(
    {
      id: '/project/$projectId/task/$taskId_',
      path: '/project/$projectId/task/$taskId',
      getParentRoute: () => LayoutAuthenticatedDashboardTeamTeamIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device/': typeof DeviceIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/dashboard/team/$teamId': typeof LayoutAuthenticatedDashboardTeamTeamIdRouteWithChildren
  '/dashboard/team/create': typeof LayoutAuthenticatedDashboardTeamCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/admin/ai': typeof LayoutAuthenticatedDashboardSettingsAdminAiRoute
  '/dashboard/settings/admin/teams': typeof LayoutAuthenticatedDashboardSettingsAdminTeamsRouteWithChildren
  '/dashboard/settings/admin/users': typeof LayoutAuthenticatedDashboardSettingsAdminUsersRoute
  '/dashboard/team/$teamId/members': typeof LayoutAuthenticatedDashboardTeamTeamIdMembersRoute
  '/dashboard/team/$teamId/search': typeof LayoutAuthenticatedDashboardTeamTeamIdSearchRoute
  '/dashboard/team/$teamId/': typeof LayoutAuthenticatedDashboardTeamTeamIdIndexRoute
  '/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/dashboard/settings/admin/teams/$teamId/labels': typeof LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRoute
  '/dashboard/team/$teamId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRoute
  '/dashboard/team/$teamId/project/$projectId/board': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRoute
  '/dashboard/team/$teamId/project/$projectId/chat': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRoute
  '/dashboard/team/$teamId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRoute
  '/dashboard/team/$teamId/project/$projectId/': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRoute
  '/dashboard/team/$teamId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device': typeof DeviceIndexRoute
  '/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/dashboard': typeof LayoutAuthenticatedDashboardIndexRoute
  '/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/dashboard/team/create': typeof LayoutAuthenticatedDashboardTeamCreateRoute
  '/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/dashboard/settings/admin/ai': typeof LayoutAuthenticatedDashboardSettingsAdminAiRoute
  '/dashboard/settings/admin/teams': typeof LayoutAuthenticatedDashboardSettingsAdminTeamsRouteWithChildren
  '/dashboard/settings/admin/users': typeof LayoutAuthenticatedDashboardSettingsAdminUsersRoute
  '/dashboard/team/$teamId/members': typeof LayoutAuthenticatedDashboardTeamTeamIdMembersRoute
  '/dashboard/team/$teamId/search': typeof LayoutAuthenticatedDashboardTeamTeamIdSearchRoute
  '/dashboard/team/$teamId': typeof LayoutAuthenticatedDashboardTeamTeamIdIndexRoute
  '/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/dashboard/settings/admin/teams/$teamId/labels': typeof LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRoute
  '/dashboard/team/$teamId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRoute
  '/dashboard/team/$teamId/project/$projectId/board': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRoute
  '/dashboard/team/$teamId/project/$projectId/chat': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRoute
  '/dashboard/team/$teamId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRoute
  '/dashboard/team/$teamId/project/$projectId': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRoute
  '/dashboard/team/$teamId/project/$projectId/task/$taskId': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/device': typeof DeviceRouteWithChildren
  '/test-error': typeof TestErrorRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/auth/check-email': typeof AuthCheckEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/device/approve': typeof DeviceApproveRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/public-project/$projectId': typeof PublicProjectProjectIdRoute
  '/device/': typeof DeviceIndexRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRouteWithChildren
  '/_layout/_authenticated/profile-setup': typeof LayoutAuthenticatedProfileSetupRoute
  '/_layout/_authenticated/dashboard/settings': typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  '/_layout/_authenticated/dashboard/': typeof LayoutAuthenticatedDashboardIndexRoute
  '/_layout/_authenticated/dashboard/settings/account': typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/projects': typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  '/_layout/_authenticated/dashboard/team/$teamId': typeof LayoutAuthenticatedDashboardTeamTeamIdRouteWithChildren
  '/_layout/_authenticated/dashboard/team/create': typeof LayoutAuthenticatedDashboardTeamCreateRoute
  '/_layout/_authenticated/dashboard/settings/account/developer': typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  '/_layout/_authenticated/dashboard/settings/account/information': typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  '/_layout/_authenticated/dashboard/settings/account/notifications': typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  '/_layout/_authenticated/dashboard/settings/account/preferences': typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
  '/_layout/_authenticated/dashboard/settings/admin/ai': typeof LayoutAuthenticatedDashboardSettingsAdminAiRoute
  '/_layout/_authenticated/dashboard/settings/admin/teams': typeof LayoutAuthenticatedDashboardSettingsAdminTeamsRouteWithChildren
  '/_layout/_authenticated/dashboard/settings/admin/users': typeof LayoutAuthenticatedDashboardSettingsAdminUsersRoute
  '/_layout/_authenticated/dashboard/team/$teamId/members': typeof LayoutAuthenticatedDashboardTeamTeamIdMembersRoute
  '/_layout/_authenticated/dashboard/team/$teamId/search': typeof LayoutAuthenticatedDashboardTeamTeamIdSearchRoute
  '/_layout/_authenticated/dashboard/team/$teamId/': typeof LayoutAuthenticatedDashboardTeamTeamIdIndexRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/general': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow': typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
  '/_layout/_authenticated/dashboard/settings/admin/teams/$teamId/labels': typeof LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRoute
  '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/backlog': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRoute
  '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/board': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRoute
  '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/chat': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRoute
  '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/gantt': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRoute
  '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRoute
  '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/task/$taskId_': typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/mcp/authorize'
    | '/public-project/$projectId'
    | '/device/'
    | '/dashboard'
    | '/profile-setup'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/account'
    | '/dashboard/settings/projects'
    | '/dashboard/team/$teamId'
    | '/dashboard/team/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/admin/ai'
    | '/dashboard/settings/admin/teams'
    | '/dashboard/settings/admin/users'
    | '/dashboard/team/$teamId/members'
    | '/dashboard/team/$teamId/search'
    | '/dashboard/team/$teamId/'
    | '/dashboard/settings/projects/$projectId/general'
    | '/dashboard/settings/projects/$projectId/integrations'
    | '/dashboard/settings/projects/$projectId/visibility'
    | '/dashboard/settings/projects/$projectId/workflow'
    | '/dashboard/settings/admin/teams/$teamId/labels'
    | '/dashboard/team/$teamId/project/$projectId/backlog'
    | '/dashboard/team/$teamId/project/$projectId/board'
    | '/dashboard/team/$teamId/project/$projectId/chat'
    | '/dashboard/team/$teamId/project/$projectId/gantt'
    | '/dashboard/team/$teamId/project/$projectId/'
    | '/dashboard/team/$teamId/project/$projectId/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/test-error'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/mcp/authorize'
    | '/public-project/$projectId'
    | '/device'
    | '/profile-setup'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/settings/account'
    | '/dashboard/settings/projects'
    | '/dashboard/team/create'
    | '/dashboard/settings/account/developer'
    | '/dashboard/settings/account/information'
    | '/dashboard/settings/account/notifications'
    | '/dashboard/settings/account/preferences'
    | '/dashboard/settings/admin/ai'
    | '/dashboard/settings/admin/teams'
    | '/dashboard/settings/admin/users'
    | '/dashboard/team/$teamId/members'
    | '/dashboard/team/$teamId/search'
    | '/dashboard/team/$teamId'
    | '/dashboard/settings/projects/$projectId/general'
    | '/dashboard/settings/projects/$projectId/integrations'
    | '/dashboard/settings/projects/$projectId/visibility'
    | '/dashboard/settings/projects/$projectId/workflow'
    | '/dashboard/settings/admin/teams/$teamId/labels'
    | '/dashboard/team/$teamId/project/$projectId/backlog'
    | '/dashboard/team/$teamId/project/$projectId/board'
    | '/dashboard/team/$teamId/project/$projectId/chat'
    | '/dashboard/team/$teamId/project/$projectId/gantt'
    | '/dashboard/team/$teamId/project/$projectId'
    | '/dashboard/team/$teamId/project/$projectId/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/device'
    | '/test-error'
    | '/_layout/_authenticated'
    | '/auth/check-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-otp'
    | '/device/approve'
    | '/mcp/authorize'
    | '/public-project/$projectId'
    | '/device/'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_authenticated/profile-setup'
    | '/_layout/_authenticated/dashboard/settings'
    | '/_layout/_authenticated/dashboard/'
    | '/_layout/_authenticated/dashboard/settings/account'
    | '/_layout/_authenticated/dashboard/settings/projects'
    | '/_layout/_authenticated/dashboard/team/$teamId'
    | '/_layout/_authenticated/dashboard/team/create'
    | '/_layout/_authenticated/dashboard/settings/account/developer'
    | '/_layout/_authenticated/dashboard/settings/account/information'
    | '/_layout/_authenticated/dashboard/settings/account/notifications'
    | '/_layout/_authenticated/dashboard/settings/account/preferences'
    | '/_layout/_authenticated/dashboard/settings/admin/ai'
    | '/_layout/_authenticated/dashboard/settings/admin/teams'
    | '/_layout/_authenticated/dashboard/settings/admin/users'
    | '/_layout/_authenticated/dashboard/team/$teamId/members'
    | '/_layout/_authenticated/dashboard/team/$teamId/search'
    | '/_layout/_authenticated/dashboard/team/$teamId/'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
    | '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
    | '/_layout/_authenticated/dashboard/settings/admin/teams/$teamId/labels'
    | '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/backlog'
    | '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/board'
    | '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/chat'
    | '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/gantt'
    | '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/'
    | '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/task/$taskId_'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DeviceRoute: typeof DeviceRouteWithChildren
  TestErrorRoute: typeof TestErrorRoute
  McpAuthorizeRoute: typeof McpAuthorizeRoute
  PublicProjectProjectIdRoute: typeof PublicProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/check-email': {
      id: '/auth/check-email'
      path: '/check-email'
      fullPath: '/auth/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/device/': {
      id: '/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof DeviceIndexRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/mcp/authorize': {
      id: '/mcp/authorize'
      path: '/mcp/authorize'
      fullPath: '/mcp/authorize'
      preLoaderRoute: typeof McpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-project/$projectId': {
      id: '/public-project/$projectId'
      path: '/public-project/$projectId'
      fullPath: '/public-project/$projectId'
      preLoaderRoute: typeof PublicProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/profile-setup': {
      id: '/_layout/_authenticated/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof LayoutAuthenticatedProfileSetupRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/dashboard/': {
      id: '/_layout/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings': {
      id: '/_layout/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings/account': {
      id: '/_layout/_authenticated/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects': {
      id: '/_layout/_authenticated/dashboard/settings/projects'
      path: '/projects'
      fullPath: '/dashboard/settings/projects'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId': {
      id: '/_layout/_authenticated/dashboard/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/dashboard/team/$teamId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/team/create': {
      id: '/_layout/_authenticated/dashboard/team/create'
      path: '/team/create'
      fullPath: '/dashboard/team/create'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamCreateRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/developer': {
      id: '/_layout/_authenticated/dashboard/settings/account/developer'
      path: '/developer'
      fullPath: '/dashboard/settings/account/developer'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/information': {
      id: '/_layout/_authenticated/dashboard/settings/account/information'
      path: '/information'
      fullPath: '/dashboard/settings/account/information'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/notifications': {
      id: '/_layout/_authenticated/dashboard/settings/account/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/account/notifications'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/account/preferences': {
      id: '/_layout/_authenticated/dashboard/settings/account/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/account/preferences'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRoute
    }
    '/_layout/_authenticated/dashboard/settings/admin/ai': {
      id: '/_layout/_authenticated/dashboard/settings/admin/ai'
      path: '/admin/ai'
      fullPath: '/dashboard/settings/admin/ai'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAdminAiRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/admin/teams': {
      id: '/_layout/_authenticated/dashboard/settings/admin/teams'
      path: '/admin/teams'
      fullPath: '/dashboard/settings/admin/teams'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAdminTeamsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/settings/admin/users': {
      id: '/_layout/_authenticated/dashboard/settings/admin/users'
      path: '/admin/users'
      fullPath: '/dashboard/settings/admin/users'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAdminUsersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/'
      path: '/'
      fullPath: '/dashboard/team/$teamId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/members': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/members'
      path: '/members'
      fullPath: '/dashboard/team/$teamId/members'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdMembersRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/search': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/search'
      path: '/search'
      fullPath: '/dashboard/team/$teamId/search'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdSearchRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/general': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/general'
      path: '/$projectId/general'
      fullPath: '/dashboard/settings/projects/$projectId/general'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/integrations'
      path: '/$projectId/integrations'
      fullPath: '/dashboard/settings/projects/$projectId/integrations'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/visibility'
      path: '/$projectId/visibility'
      fullPath: '/dashboard/settings/projects/$projectId/visibility'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow': {
      id: '/_layout/_authenticated/dashboard/settings/projects/$projectId/workflow'
      path: '/$projectId/workflow'
      fullPath: '/dashboard/settings/projects/$projectId/workflow'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRoute
    }
    '/_layout/_authenticated/dashboard/settings/admin/teams/$teamId/labels': {
      id: '/_layout/_authenticated/dashboard/settings/admin/teams/$teamId/labels'
      path: '/$teamId/labels'
      fullPath: '/dashboard/settings/admin/teams/$teamId/labels'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardSettingsAdminTeamsRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/dashboard/team/$teamId/project/$projectId/'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/backlog': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/backlog'
      path: '/project/$projectId/backlog'
      fullPath: '/dashboard/team/$teamId/project/$projectId/backlog'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/board': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/board'
      path: '/project/$projectId/board'
      fullPath: '/dashboard/team/$teamId/project/$projectId/board'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/chat': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/chat'
      path: '/project/$projectId/chat'
      fullPath: '/dashboard/team/$teamId/project/$projectId/chat'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/gantt': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/gantt'
      path: '/project/$projectId/gantt'
      fullPath: '/dashboard/team/$teamId/project/$projectId/gantt'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
    '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/task/$taskId_': {
      id: '/_layout/_authenticated/dashboard/team/$teamId/project/$projectId/task/$taskId_'
      path: '/project/$projectId/task/$taskId'
      fullPath: '/dashboard/team/$teamId/project/$projectId/task/$taskId'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRouteImport
      parentRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRoute
    }
  }
}

interface LayoutAuthenticatedDashboardSettingsAccountRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute: typeof LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute
  LayoutAuthenticatedDashboardSettingsAccountInformationRoute: typeof LayoutAuthenticatedDashboardSettingsAccountInformationRoute
  LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute: typeof LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute
  LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute: typeof LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute
}

const LayoutAuthenticatedDashboardSettingsAccountRouteChildren: LayoutAuthenticatedDashboardSettingsAccountRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute:
      LayoutAuthenticatedDashboardSettingsAccountDeveloperRoute,
    LayoutAuthenticatedDashboardSettingsAccountInformationRoute:
      LayoutAuthenticatedDashboardSettingsAccountInformationRoute,
    LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute:
      LayoutAuthenticatedDashboardSettingsAccountNotificationsRoute,
    LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute:
      LayoutAuthenticatedDashboardSettingsAccountPreferencesRoute,
  }

const LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsAccountRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsAccountRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsProjectsRouteChildren {
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute
  LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute
}

const LayoutAuthenticatedDashboardSettingsProjectsRouteChildren: LayoutAuthenticatedDashboardSettingsProjectsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdGeneralRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdIntegrationsRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdVisibilityRoute,
    LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute:
      LayoutAuthenticatedDashboardSettingsProjectsProjectIdWorkflowRoute,
  }

const LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsProjectsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsProjectsRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsAdminTeamsRouteChildren {
  LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRoute: typeof LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRoute
}

const LayoutAuthenticatedDashboardSettingsAdminTeamsRouteChildren: LayoutAuthenticatedDashboardSettingsAdminTeamsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRoute:
      LayoutAuthenticatedDashboardSettingsAdminTeamsTeamIdLabelsRoute,
  }

const LayoutAuthenticatedDashboardSettingsAdminTeamsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsAdminTeamsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsAdminTeamsRouteChildren,
  )

interface LayoutAuthenticatedDashboardSettingsRouteChildren {
  LayoutAuthenticatedDashboardSettingsAccountRoute: typeof LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren
  LayoutAuthenticatedDashboardSettingsProjectsRoute: typeof LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren
  LayoutAuthenticatedDashboardSettingsAdminAiRoute: typeof LayoutAuthenticatedDashboardSettingsAdminAiRoute
  LayoutAuthenticatedDashboardSettingsAdminTeamsRoute: typeof LayoutAuthenticatedDashboardSettingsAdminTeamsRouteWithChildren
  LayoutAuthenticatedDashboardSettingsAdminUsersRoute: typeof LayoutAuthenticatedDashboardSettingsAdminUsersRoute
}

const LayoutAuthenticatedDashboardSettingsRouteChildren: LayoutAuthenticatedDashboardSettingsRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsAccountRoute:
      LayoutAuthenticatedDashboardSettingsAccountRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsProjectsRoute:
      LayoutAuthenticatedDashboardSettingsProjectsRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsAdminAiRoute:
      LayoutAuthenticatedDashboardSettingsAdminAiRoute,
    LayoutAuthenticatedDashboardSettingsAdminTeamsRoute:
      LayoutAuthenticatedDashboardSettingsAdminTeamsRouteWithChildren,
    LayoutAuthenticatedDashboardSettingsAdminUsersRoute:
      LayoutAuthenticatedDashboardSettingsAdminUsersRoute,
  }

const LayoutAuthenticatedDashboardSettingsRouteWithChildren =
  LayoutAuthenticatedDashboardSettingsRoute._addFileChildren(
    LayoutAuthenticatedDashboardSettingsRouteChildren,
  )

interface LayoutAuthenticatedDashboardTeamTeamIdRouteChildren {
  LayoutAuthenticatedDashboardTeamTeamIdMembersRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdMembersRoute
  LayoutAuthenticatedDashboardTeamTeamIdSearchRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdSearchRoute
  LayoutAuthenticatedDashboardTeamTeamIdIndexRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdIndexRoute
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRoute
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRoute
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRoute
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRoute
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRoute
  LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRoute
}

const LayoutAuthenticatedDashboardTeamTeamIdRouteChildren: LayoutAuthenticatedDashboardTeamTeamIdRouteChildren =
  {
    LayoutAuthenticatedDashboardTeamTeamIdMembersRoute:
      LayoutAuthenticatedDashboardTeamTeamIdMembersRoute,
    LayoutAuthenticatedDashboardTeamTeamIdSearchRoute:
      LayoutAuthenticatedDashboardTeamTeamIdSearchRoute,
    LayoutAuthenticatedDashboardTeamTeamIdIndexRoute:
      LayoutAuthenticatedDashboardTeamTeamIdIndexRoute,
    LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRoute:
      LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBacklogRoute,
    LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRoute:
      LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdBoardRoute,
    LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRoute:
      LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdChatRoute,
    LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRoute:
      LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdGanttRoute,
    LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRoute:
      LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdIndexRoute,
    LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRoute:
      LayoutAuthenticatedDashboardTeamTeamIdProjectProjectIdTaskTaskIdRoute,
  }

const LayoutAuthenticatedDashboardTeamTeamIdRouteWithChildren =
  LayoutAuthenticatedDashboardTeamTeamIdRoute._addFileChildren(
    LayoutAuthenticatedDashboardTeamTeamIdRouteChildren,
  )

interface LayoutAuthenticatedDashboardRouteChildren {
  LayoutAuthenticatedDashboardSettingsRoute: typeof LayoutAuthenticatedDashboardSettingsRouteWithChildren
  LayoutAuthenticatedDashboardIndexRoute: typeof LayoutAuthenticatedDashboardIndexRoute
  LayoutAuthenticatedDashboardTeamTeamIdRoute: typeof LayoutAuthenticatedDashboardTeamTeamIdRouteWithChildren
  LayoutAuthenticatedDashboardTeamCreateRoute: typeof LayoutAuthenticatedDashboardTeamCreateRoute
}

const LayoutAuthenticatedDashboardRouteChildren: LayoutAuthenticatedDashboardRouteChildren =
  {
    LayoutAuthenticatedDashboardSettingsRoute:
      LayoutAuthenticatedDashboardSettingsRouteWithChildren,
    LayoutAuthenticatedDashboardIndexRoute:
      LayoutAuthenticatedDashboardIndexRoute,
    LayoutAuthenticatedDashboardTeamTeamIdRoute:
      LayoutAuthenticatedDashboardTeamTeamIdRouteWithChildren,
    LayoutAuthenticatedDashboardTeamCreateRoute:
      LayoutAuthenticatedDashboardTeamCreateRoute,
  }

const LayoutAuthenticatedDashboardRouteWithChildren =
  LayoutAuthenticatedDashboardRoute._addFileChildren(
    LayoutAuthenticatedDashboardRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRouteWithChildren
  LayoutAuthenticatedProfileSetupRoute: typeof LayoutAuthenticatedProfileSetupRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute:
    LayoutAuthenticatedDashboardRouteWithChildren,
  LayoutAuthenticatedProfileSetupRoute: LayoutAuthenticatedProfileSetupRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DeviceRouteChildren {
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceIndexRoute: typeof DeviceIndexRoute
}

const DeviceRouteChildren: DeviceRouteChildren = {
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceIndexRoute: DeviceIndexRoute,
}

const DeviceRouteWithChildren =
  DeviceRoute._addFileChildren(DeviceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DeviceRoute: DeviceRouteWithChildren,
  TestErrorRoute: TestErrorRoute,
  McpAuthorizeRoute: McpAuthorizeRoute,
  PublicProjectProjectIdRoute: PublicProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
